### ISSUE TITLE
Can not set the second line of the billing address

### ISSUE THREAD

**Issue by FGRCL** [paypal/payflow-gateway#13]
### General information

* SDK/Library version: 4.4.6
* Environment: n/a
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: Java, JDK 11, macOS

### Issue description
According to the Payflow documentation there exists a "BILLTOADDRESS2" for the NVPs (https://developer.paypal.com/docs/payflow/integration-guide/submit-transactions/#core-credit-card-parameters). However, the BillTo object in the Java SDK does not have a method to set that NVP's value. Furthermore, the example "DOSaleComplete" has the following lines which do not compile
```
bill.setStreet("123 Main St.");
// Secondary street address.
bill.setBillToStreet2("Suite A"); //does not compile because setBillToStreet2 does not exist
```

**Comment by awesmdiver** [comment]
Fixed in v4.47.
