### ISSUE TITLE
C# assembly upgraded in Visual Studio, assembly shows but compile fails

### ISSUE THREAD

**Issue by felix3754** [paypal/payflow-gateway#3]
We are trying to replace an older version of the assembly (4.3.10) with the new version for TLS 1.2 support (Payflow_dotNET_4.45_TLS1.2.zip) in Visual Studio. We have removed the old assembly, then added the new one. It shows up correctly, the class browser shows all the usual PayPal.Payments classes in the assembly, Intellisense works etc. But compilation fails with the information that the PayPal namespace can not be found (are we missing an assembly or using directive?). 

Tried this on two windows computers running Windows 7, both have .NET framework 4.5 or above installed. Compilation fails. Created a new Class Library project, with just the new assembly. Also failed. 

Downloaded earlier release candidate zip file "Payflow_dotNET_v4.50RC.zip" from Github and added that assembly. Now the problem does not occur. Now the project compiles. What changed from the release candidate to the 4.45 release? Might there be some additional dependency that this assembly has and which we need to add to our project? 

We are using Visual Studio 2013 (sorry) - but I don't think that should be  the problem. 

Thank you for your help.

**Comment by awesmdiver** [comment]
When did you download the SDK from Github?  I just posted a new version that is compatible with 4.5 as stated.  The build up was compiled using 4.61.

**Comment by felix3754** [comment]
Awesome speed! Thank you for your reply. Downloaded about 2 hours ago. Will try your new version right away. Thanks.

**Comment by felix3754** [comment]
Thank you very much! Compiles now! Problem resolved.
Is the .tlb file intentially missing from the zip? 
Thank you for the quick response!

**Comment by awesmdiver** [comment]
Well I was to lazy to add it.  Let me get it and I'll let you know.

On May 24, 2018 3:28 PM, felix3754 <notifications@github.com> wrote:

Thank you very much! Compiles now! Problem resolved.
Is the .tlb file intentially missing from the zip?
Thank you for the quick response!

**Comment by awesmdiver** [comment]
Ok, new package is uploaded – with all files.

**Comment by boonlert788** [comment]
https://my.leadpages.net/onboarding/set-subdomain
