### ISSUE TITLE
The library version contained in zip file Payflow_dotNET_SDK_v447.zip indicates 4.4.6

### ISSUE THREAD

**Issue by ronnymgm** [paypal/payflow-gateway#31]
Helllo PayPal Team, we just downloaded the latest payflow sdk for .net and noticed the version is not correct.

**Describe the bug**
The library contained in zip file Payflow_dotNET_SDK_v447.zip version iindicates 4.4.6.
File Size and Content are different but the version still indicates the previous one.

**To Reproduce**
Download the zip file and right click on the library properties for Version details.

**Expected behavior**
The library (DLL) version should match the folder name and content.

**Screenshots**
![image](https://user-images.githubusercontent.com/3348128/97762374-ef47a580-1acd-11eb-9757-57470bca2372.png)

Thanks.

**Comment by Sharina31** [comment]
Na

**Comment by Sharina31** [comment]
> Helllo PayPal Team, we just downloaded the latest payflow sdk for .net and noticed the version is not correct.
> 
> **Describe the bug**
> The library contained in zip file Payflow_dotNET_SDK_v447.zip version iindicates 4.4.6.
> File Size and Content are different but the version still indicates the previous one.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Download the zip file and right click on the library properties for Version details.
> 
> **Expected behavior**
> The library (DLL) version should match the folder name and content.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/3348128/97762374-ef47a580-1acd-11eb-9757-57470bca2372.png)
> 
> Thanks.

**Comment by Sharina31** [comment]
> Helllo PayPal Team, we just downloaded the latest payflow sdk for .net and noticed the version is not correct.
> 
> **Describe the bug**
> The library contained in zip file Payflow_dotNET_SDK_v447.zip version iindicates 4.4.6.
> File Size and Content are different but the version still indicates the previous one.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Download the zip file and right click on the library properties for Version details.
> 
> **Expected behavior**
> The library (DLL) version should match the folder name and content.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/3348128/97762374-ef47a580-1acd-11eb-9757-57470bca2372.png)
> 
> Thanks.

**Comment by awesmdiver** [comment]
File version has been corrected and uploaded to SDK Binaries. No other changes to .dll are made.
