### ISSUE TITLE
Payflow Java SDK is using JDK11 removed internal API

### ISSUE THREAD

**Issue by sam-ma** [paypal/payflow-gateway#6]
### General information

* SDK/Library version: Payflow_SDK_for_Java_v441_TLS.zip
* Environment: 
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: JDK11

### Issue description

```
$ jdeps --jdk-internals payflow_v441.jar 
payflow_v441.jar -> JDK removed internal API
   paypal.payflow.PaymentConnection                   -> sun.misc.BASE64Encoder                             JDK internal API (JDK removed internal API)

Warning: JDK internal APIs are unsupported and private to JDK implementation that are
subject to be removed or changed incompatibly and could break your application.
Please modify your code to eliminate dependence on any JDK internal APIs.
For the most recent update on JDK internal API replacements, please check:
https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool

JDK Internal API                         Suggested Replacement
----------------                         ---------------------
sun.misc.BASE64Encoder                   Use java.util.Base64 @since 1.8
```

Is there any plan to update the SDK to fix this?

**Comment by awesmdiver** [comment]
At some point this SDK will be open-sourced, but I think I have resolved the issue above but don't have the means to test it.  Please reach out to DL-PayPal-Payflow-SDK@paypal.com and I can provide you a new .jar file.

**Comment by paulaparker6614** [comment]
> ### General information
> * SDK/Library version: Payflow_SDK_for_Java_v441_TLS.zip
> * Environment:
> * `PayPal-Debug-ID` values:
> * Language, language version, and OS: JDK11
> 
> ### Issue description
> ```
> $ jdeps --jdk-internals payflow_v441.jar 
> payflow_v441.jar -> JDK removed internal API
>    paypal.payflow.PaymentConnection                   -> sun.misc.BASE64Encoder                             JDK internal API (JDK removed internal API)
> 
> Warning: JDK internal APIs are unsupported and private to JDK implementation that are
> subject to be removed or changed incompatibly and could break your application.
> Please modify your code to eliminate dependence on any JDK internal APIs.
> For the most recent update on JDK internal API replacements, please check:
> https://wiki.openjdk.java.net/display/JDK8/Java+Dependency+Analysis+Tool
> 
> JDK Internal API                         Suggested Replacement
> ----------------                         ---------------------
> sun.misc.BASE64Encoder                   Use java.util.Base64 @since 1.8
> ```
> 
> Is there any plan to update the SDK to fix this?

We hope

**Comment by awesmdiver** [comment]
Source code released for new version 5.
