### ISSUE TITLE
No API docs for payflow-pro java sdk

### ISSUE THREAD

**Issue by robphilipp-tiggee** [paypal/payflow-gateway#7]
### General information

* SDK/Library version: PayFlowPro Java SDK 4.41
* Environment: n/a
* `PayPal-Debug-ID` values: 
* Language, language version, and OS: Java

### Issue description

After downloading the zip file and expanding it, was unable to find the API docs. The docs/payflow_API directory is empty. The docs directory doesn't hava it. There doesn't appear to be a sources jar.

**Comment by techieshark** [comment]
I landed on this repo after reading this doc, expecting to find docs, and found nothing.

https://developer.paypal.com/docs/classic/products/recurring-billing/?mark=recurring

**Comment by awesmdiver** [comment]
Source code for new v5 is now available.
