### ISSUE TITLE
.NET Core Compatible

### ISSUE THREAD

**Issue by jmawebtech** [paypal/payflow-gateway#8]
Hi,

Is this library compatible with .NET Core compatible? If not, can you add this feature or share the source code? Is there another SDK that I can use?

**Comment by aaronralls** [comment]
Have you tried to use it? It shouldn’t be a problem. It should be no different than using EF 6 with a .Net Core web application.

**Comment by awesmdiver** [comment]
Just uploaded a build of v.4.4.6 compiled for .NET Core v2.2.1, see https://github.com/paypal/payflow-gateway/tree/master/dotNET.
